### Part-1 --> Regression Algorithm

## Task-1 ---> Linear Regression

In [312]:
import pandas as pd
import csv
df = pd.read_csv(
    'household_power_consumption.csv',
    sep=';',
    na_values='?',
    encoding='latin1',
    quoting=csv.QUOTE_NONE
)
# Remove surrounding double quotes
df.columns = df.columns.str.strip('"')
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip('"')

C:\Users\pammi\AppData\Local\Temp\ipykernel_22664\1259357124.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include='object').columns:

In [313]:
df

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.000
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.000
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.000
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.000
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.000
...,...,...,...,...,...,...,...,...,...
2075254,26/11/2010,20:58:00,0.946,0.000,240.43,4.0,0.0,0.0,0.000
2075255,26/11/2010,20:59:00,0.944,0.000,240.00,4.0,0.0,0.0,0.000
2075256,26/11/2010,21:00:00,0.938,0.000,239.82,3.8,0.0,0.0,0.000
2075257,26/11/2010,21:01:00,0.934,0.000,239.70,3.8,0.0,0.0,0.000
2075258,26/11/2010,21:02:00,0.932,0.000,239.55,3.8,0.0,0.0,0.000

In [314]:
df['Datetime'] = pd.to_datetime(
    df['Date'] + ' ' + df['Time'],
    format='%d/%m/%Y %H:%M:%S'
)

In [315]:
df

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Datetime
0,16/12/2006,17:24:00,4.216,0.418,234.84,18.4,0.0,1.0,17.000,2006-12-16 17:24:00
1,16/12/2006,17:25:00,5.360,0.436,233.63,23.0,0.0,1.0,16.000,2006-12-16 17:25:00
2,16/12/2006,17:26:00,5.374,0.498,233.29,23.0,0.0,2.0,17.000,2006-12-16 17:26:00
3,16/12/2006,17:27:00,5.388,0.502,233.74,23.0,0.0,1.0,17.000,2006-12-16 17:27:00
4,16/12/2006,17:28:00,3.666,0.528,235.68,15.8,0.0,1.0,17.000,2006-12-16 17:28:00
...,...,...,...,...,...,...,...,...,...,...
2075254,26/11/2010,20:58:00,0.946,0.000,240.43,4.0,0.0,0.0,0.000,2010-11-26 20:58:00
2075255,26/11/2010,20:59:00,0.944,0.000,240.00,4.0,0.0,0.0,0.000,2010-11-26 20:59:00
2075256,26/11/2010,21:00:00,0.938,0.000,239.82,3.8,0.0,0.0,0.000,2010-11-26 21:00:00
2075257,26/11/2010,21:01:00,0.934,0.000,239.70,3.8,0.0,0.0,0.000,2010-11-26 21:01:00
2075258,26/11/2010,21:02:00,0.932,0.000,239.55,3.8,0.0,0.0,0.000,2010-11-26 21:02:00

In [316]:
df['Year'] = df['Datetime'].dt.year
df['Month'] = df['Datetime'].dt.month
df['Day'] = df['Datetime'].dt.day
df['Hour'] = df['Datetime'].dt.hour
df['Minute'] = df['Datetime'].dt.minute
df['DayOfWeek'] = df['Datetime'].dt.dayofweek
df['IsWeekend'] = (df['DayOfWeek'] >= 5).astype(int)
df.drop(columns=['Date', 'Time', 'Datetime'], inplace=True)

In [317]:
df

,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Year,Month,Day,Hour,Minute,DayOfWeek,IsWeekend
0,4.216,0.418,234.84,18.4,0.0,1.0,17.000,2006,12,16,17,24,5,1
1,5.360,0.436,233.63,23.0,0.0,1.0,16.000,2006,12,16,17,25,5,1
2,5.374,0.498,233.29,23.0,0.0,2.0,17.000,2006,12,16,17,26,5,1
3,5.388,0.502,233.74,23.0,0.0,1.0,17.000,2006,12,16,17,27,5,1
4,3.666,0.528,235.68,15.8,0.0,1.0,17.000,2006,12,16,17,28,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2075254,0.946,0.000,240.43,4.0,0.0,0.0,0.000,2010,11,26,20,58,4,0
2075255,0.944,0.000,240.00,4.0,0.0,0.0,0.000,2010,11,26,20,59,4,0
2075256,0.938,0.000,239.82,3.8,0.0,0.0,0.000,2010,11,26,21,0,4,0
2075257,0.934,0.000,239.70,3.8,0.0,0.0,0.000,2010,11,26,21,1,4,0
2075258,0.932,0.000,239.55,3.8,0.0,0.0,0.000,2010,11,26,21,2,4,0

In [318]:
numerical_data = [
    'Global_active_power',
    'Global_reactive_power',
    'Voltage',
    'Global_intensity',
    'Sub_metering_1',
    'Sub_metering_2',
    'Sub_metering_3'
]

for col in numerical_data:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [319]:
df=df[['Global_active_power','Global_reactive_power','Voltage','Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3','Month','Hour','DayOfWeek','IsWeekend']]

In [320]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 11 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Global_active_power    float64
 1   Global_reactive_power  float64
 2   Voltage                float64
 3   Global_intensity       float64
 4   Sub_metering_1         float64
 5   Sub_metering_2         float64
 6   Sub_metering_3         float64
 7   Month                  int32
 8   Hour                   int32
 9   DayOfWeek              int32
 10  IsWeekend              int64
dtypes: float64(7), int32(3), int64(1)
memory usage: 150.4 MB

In [321]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
numerical_Pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='median')),('scaling',StandardScaler())])
numerical_data=['Global_reactive_power','Voltage','Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3','Month','Hour','DayOfWeek','IsWeekend']
features=ColumnTransformer(transformers=[('Numerical_Transformation',numerical_Pipeline,numerical_data)])
df = df.dropna(subset=['Global_active_power'])

In [322]:
X=df.drop(columns=['Global_active_power'])
Y=df['Global_active_power']

In [323]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [324]:
from sklearn.linear_model import LinearRegression
model=Pipeline(steps=[('features',features),('regressor',LinearRegression())])
model.fit(X_train,Y_train)
y_pred=model.predict(X_test)

### Task-2

In [325]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np
mae = mean_absolute_error(Y_test, y_pred)

mse = mean_squared_error(Y_test, y_pred)

rmse = np.sqrt(mse)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)

MAE: 0.025820183859701227
MSE: 0.0016449412296120828
RMSE: 0.04055787506282945

## Task-7 ----> Overfitting & Underfitting

In [326]:
from sklearn.metrics import r2_score 
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)
print("Training R2:", r2_score(Y_train, train_pred))
print("Testing R2:", r2_score(Y_test, test_pred))

Training R2: 0.9985328353321495
Testing R2: 0.9985296300634964

In [327]:
from sklearn.tree import DecisionTreeRegressor
complex_model = Pipeline(steps=[
    ('features', features),
    ('regressor', DecisionTreeRegressor(
        max_depth=None,
        min_samples_split=2,
        min_samples_leaf=1,
        random_state=42
    ))
])
complex_model.fit(X_train, Y_train)
train_pred_complex = complex_model.predict(X_train)
test_pred_complex = complex_model.predict(X_test)

print("Training R2:", r2_score(Y_train, train_pred_complex))
print("Testing R2:", r2_score(Y_test, test_pred_complex))

c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\extmath.py:1234: RuntimeWarning: overflow encountered in square
  temp **= 2
c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\extmath.py:1240: RuntimeWarning: overflow encountered in square
  new_unnormalized_variance -= correction**2 / new_sample_count
c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\extmath.py:1240: RuntimeWarning: invalid value encountered in subtract
  new_unnormalized_variance -= correction**2 / new_sample_count
c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\preprocessing\_data.py:97: RuntimeWarning: overflow encountered in square
  upper_bound = n_samples * eps * var + (n_samples * mean * eps) ** 2
c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_array_api.py:983: RuntimeWarning: overflow encountered in cast
  array = numpy.asarray(array, order=order, dtype=dtype)
c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages\numpy\_core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: Input X contains infinity or a value too large for dtype('float32').

In [ ]:

comparison = pd.DataFrame({
    'Model': ['Simple Model', 'Complex Model'],
    'Training R2': [
        r2_score(Y_train, train_pred),
        r2_score(Y_train, train_pred_complex)
    ],
    'Testing R2': [
        r2_score(Y_test, test_pred),
        r2_score(Y_test, test_pred_complex)
    ]
})

print(comparison)

           Model  Training R2  Testing R2
0   Simple Model     0.043618    0.064835
1  Complex Model     1.000000   -0.248337

### Part-3 ----> Classification Algorithms

## Task-3 --> Logistic Regression

In [ ]:

import sklearn
bank=pd.read_csv('bank-full.csv',sep=';')

In [ ]:
bank

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [ ]:
bank=bank[['age','job','education','balance','housing','loan','contact','month','duration','campaign','pdays','previous','poutcome','y']]

In [ ]:
numerical_data=['age','balance','duration','campaign','pdays','previous']
ordinal_data=['education']
nominal_data=['job','housing','loan','contact','month','poutcome']

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

In [ ]:
numerical_Pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='median')),('scaling',StandardScaler())])
ordinal_Pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),('encoding',OrdinalEncoder(categories=[['unknown','primary','secondary','tertiary']])),('scaling',StandardScaler())])
nominal_Pipeline=Pipeline(steps=[('impute',SimpleImputer(strategy='most_frequent')),('encoding',OneHotEncoder(handle_unknown='ignore'))])

In [ ]:
features=ColumnTransformer(transformers=[('Numerical_Transformation',numerical_Pipeline,numerical_data),('Ordinal_Transformation',ordinal_Pipeline,ordinal_data),('Nominal_Transformation',nominal_Pipeline,nominal_data)])

In [ ]:
features

ColumnTransformer(transformers=[('Numerical_Transformation',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['age', 'balance', 'duration', 'campaign',
                                  'pdays', 'previous']),
                                ('Ordinal_Transformation',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OrdinalEncoder(categories=[['unknown',
                                                                              'primary',
                                                                              'secondary',
                                                                              'tertiary']])),
                                                 ('scaling',
                                                  StandardScaler())]),
                                 ['education']),
                                ('Nominal_Transformation',
                                 Pipeline(steps=[('impute',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoding',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['job', 'housing', 'loan', 'contact', 'month',
                                  'poutcome'])])

In [ ]:
from sklearn.linear_model import LogisticRegression
model = Pipeline(steps=[('features',features),('classifier',LogisticRegression())])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=bank['y']
Y=le.fit_transform(Y)
X=bank.iloc[:,:-1]

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)
model.fit(X_train,Y_train)
y_pred=model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,Y_test)

0.9048988167643481

## Task-4 ---> GaussianNB

In [ ]:
from sklearn.naive_bayes import GaussianNB
model1=Pipeline(steps=[('features',features),('classifier',GaussianNB())])
model1.fit(X_train,Y_train)
y_pred=model1.predict(X_test)
accuracy_score(y_pred,Y_test)

0.8582328873161561

## Task-5 ----> K-Nearest Neighbors (KNN)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model2=Pipeline(steps=[('features',features),('classifier',KNeighborsClassifier(n_neighbors=17))])
model2.fit(X_train,Y_train)
y_pred=model2.predict(X_test)
accuracy_score(y_pred,Y_test)

0.9005860886873825

## Task-6 ----> Classification Metrics

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
model2.fit(X_train,Y_train)
y_pred=model2.predict(X_test)
print(precision_score(y_pred,Y_test))
print(recall_score(y_pred,Y_test))
print(f1_score(y_pred,Y_test))

0.329162656400385
0.6286764705882353
0.4320909665192672

In [ ]:
model1.fit(X_train,Y_train)
y_pred=model1.predict(X_test)
print(precision_score(y_pred,Y_test))
print(recall_score(y_pred,Y_test))
print(f1_score(y_pred,Y_test))

0.5014436958614052
0.4054474708171206
0.4483648881239243

In [ ]:
model.fit(X_train,Y_train)
y_pred=model.predict(X_test)
print(precision_score(y_pred,Y_test))
print(recall_score(y_pred,Y_test))
print(f1_score(y_pred,Y_test))

0.34648700673724736
0.6654343807763401
0.45569620253164556