#### Data Gathering for json -->json files

In [1]:
import pandas as pd

In [7]:
df=pd.read_json('iris.json')
df

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [3]:
pd.read_json('https://jsonplaceholder.typicode.com/posts')

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...
...,...,...,...,...
95,10,96,quaerat velit veniam amet cupiditate aut numqu...,in non odio excepturi sint eum\nlabore volupta...
96,10,97,quas fugiat ut perspiciatis vero provident,eum non blanditiis soluta porro quibusdam volu...
97,10,98,laboriosam dolor voluptates,doloremque ex facilis sit sint culpa\nsoluta a...
98,10,99,temporibus sit alias delectus eligendi possimu...,quo deleniti praesentium dicta non quod\naut e...
99,10,100,at nam consequatur ea labore ea harum,cupiditate quo est a modi nesciunt soluta\nips...

#### Gathering the Sql Data and then need to apply some analysis or want to build a model on it
#### mysql.connector 
#### function to connect to our database --> connect()
#### connect()->host--> server --> localhost
## connect() --> username
## connect() --> password
## connect() --> database name

In [4]:
%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (c:\Users\pammi\AppData\Local\Programs\Python\Python314\Lib\site-packages)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import mysql.connector

In [6]:
data=mysql.connector.connect(host='localhost',user='root',password='',database='world')

DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)

In [ ]:
data

In [ ]:
pd.read_sql_query('select * from city',data)

C:\Users\pammi\AppData\Local\Temp\ipykernel_22316\2442894597.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('select * from city',data)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [ ]:
ind=pd.read_sql_query('select * from city where CountryCode like "IND"',data)

C:\Users\pammi\AppData\Local\Temp\ipykernel_22316\1513916673.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ind=pd.read_sql_query('select * from city where CountryCode like "IND"',data)

In [ ]:
ind

       ID                Name CountryCode        District  Population
0    1024     Mumbai (Bombay)         IND     Maharashtra    10500000
1    1025               Delhi         IND           Delhi     7206704
2    1026  Calcutta [Kolkata]         IND    West Bengali     4399819
3    1027    Chennai (Madras)         IND      Tamil Nadu     3841396
4    1028           Hyderabad         IND  Andhra Pradesh     2964638
..    ...                 ...         ...             ...         ...
336  1360        Ambala Sadar         IND         Haryana       90712
337  1361          Baidyabati         IND    West Bengali       90601
338  1362               Morvi         IND         Gujarat       90357
339  1363             Raigarh         IND     Chhatisgarh       89166
340  1364            Vejalpur         IND         Gujarat       89053

[341 rows x 5 columns]

In [ ]:
import sqlite3
conn = sqlite3.connect("sample.db")
print("Database connected successfully!")

Database connected successfully!

In [12]:
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE IF NOT EXISTS employees (
    id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary REAL
)
""")
conn.commit()
print("Table created successfully!")

Table created successfully!

In [13]:
employees = [
    (1, "Rahul", "IT", 50000),
    (2, "Priya", "HR", 45000),
    (3, "Arjun", "IT", 60000),
    (4, "Sneha", "Finance", 55000)
]

cursor.executemany("""
INSERT INTO employees (id, name, department, salary)
VALUES (?, ?, ?, ?)
""", employees)

conn.commit()

print("Data inserted successfully!")

Data inserted successfully!

In [14]:
cursor.execute("SELECT * FROM employees")

rows = cursor.fetchall()

for row in rows:
    print(row)

(1, 'Rahul', 'IT', 50000.0)
(2, 'Priya', 'HR', 45000.0)
(3, 'Arjun', 'IT', 60000.0)
(4, 'Sneha', 'Finance', 55000.0)

In [15]:
import pandas as pd
df = pd.read_sql_query(
    "SELECT * FROM employees",
    conn
)

df

   id   name department   salary
0   1  Rahul         IT  50000.0
1   2  Priya         HR  45000.0
2   3  Arjun         IT  60000.0
3   4  Sneha    Finance  55000.0